[package]
name = "autodj"
version = "0.5.4"

description = "Automatic Differentiation Library"
authors = [
    "Maksim Elizarev <maxim.elizarev.research@gmail.com>",
    "https://djmaxus.github.io/",
]
categories = ["mathematics", "science", "simulation"]
keywords = ["automatic", "derivative", "jacobian", "dual-number", "comp-math"]
repository = "https://github.com/djmaxus/autodj"

edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default = ["std","prelude"]
std = ["num-traits/std", "uuid?/std", "no-std-compat/std"] #FIXME: make mod fluid no_std instead
sparse = ["no-std-compat/compat_hash"]
uuid = ["sparse", "dep:uuid"]
prelude = []

[dependencies.num-traits]
version = "0.2.19"
default-features = false
features = ["libm"]

[dependencies.no-std-compat] #WARNING: old stale dependency, remove
version = "0.4.1"
default-features = false
features = ["alloc"]

[dependencies.uuid]
version = "1.15.1"
default-features = false
features = ["v4"]
optional = true

[dev-dependencies]
autodiff = "0.7.0"
nalgebra = "0.33.2"

[[example]]
name = "pendulum_sparse"
required-features = ["uuid"]

[package.metadata.docs.rs]
all-features = true

[lints.rust]
missing_docs = "warn"
unreachable_pub = "warn"
private_interfaces = "warn"
private_bounds = "warn"
pub_use_of_private_extern_crate = "warn"
exported_private_dependencies = "warn"
unused = { level = "warn", priority = 1 }
unused_results = "warn"
unused_import_braces = "warn"
unused_lifetimes = "warn"
unused_qualifications = "warn"

[lints.clippy]
pedantic = { level = "warn", priority = 1 }
suspicious = { level = "warn", priority = 1 }
perf = { level = "warn", priority = 1 }
style = { level = "warn", priority = 1 }
complexity = { level = "warn", priority = 1 }
type_repetition_in_bounds = "warn"
allow_attributes_without_reason = "warn"
as_conversions = "warn"
clone_on_ref_ptr = "warn"
dbg_macro = "warn"
default_numeric_fallback = "warn"
exhaustive_enums = "warn"
expect_used = "warn"
float_cmp_const = "warn"
if_then_some_else_none = "warn"
impl_trait_in_params = "warn"
lossy_float_literal = "warn"
missing_docs_in_private_items = "warn"
redundant_pub_crate = "warn"
cargo = { level = "warn", priority = 1 }
disallowed_methods = "warn"
unwrap_used = "warn"
fallible_impl_from = "warn"
get_unwrap = "warn"
map_unwrap_or = "warn"
unnecessary_safety_comment = "warn"
unwrap_in_result = "warn"
cast_lossless = "warn"
indexing_slicing = "warn"
trivially_copy_pass_by_ref = "warn"

[lints.rustdoc]
private_doc_tests = "warn"
private_intra_doc_links = "warn"
all = "warn"
missing_crate_level_docs = "warn"

[profile.ci]
inherits = "dev"
opt-level = 0
debug = 0
lto = false
codegen-units = 16
incremental = true
panic = 'abort'


# [dependencies]
# auto_ops = ">=0"

## trying to include examples in docs.rs page
# [package.metadata.docs.rs]
# cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples=examples"]
# [[example]]
# name = "ideal_gas"
# crate-type = ["bin"]
# doc = true
# rustdoc-args = ["--scrape-examples"]
# [package.metadata.docs.rs.examples]
# "ideal_gas" = { path = "examples/ideal_gas.rs" }
