[package]
name = "autodj"
version = "0.4.4"

description = "Automatic Differentiation Library"
authors = [
    "Maksim Elizarev <maxim.elizarev.research@gmail.com>",
    "https://djmaxus.github.io/",
]
categories = ["mathematics", "science", "simulation"]
keywords = ["automatic", "derivative", "jacobian", "dual-number", "comp-math"]
repository = "https://github.com/djmaxus/autodj"

edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default = []

[dependencies]
auto_ops = "0.3.0"
nalgebra = "0.32.2"
num-traits = "0.2.15"
# num-traits = { version = ">=0", optional = true }
# rustversion = ">=0"
# nalgebra = ">=0"
# uuid = ">=0"

[dev-dependencies]
autodiff = ">=0"
# rayon = ">=0"
# threadpool = ">=0"

# [profile.release]
# debug = true

# [package.metadata.docs.rs]
# cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples=examples"]

## trying to include examples in docs.rs page
# [[example]]
# name = "ideal_gas"
# crate-type = ["bin"]
# doc = true
# rustdoc-args = ["--scrape-examples"]
# [package.metadata.docs.rs.examples]
# "ideal_gas" = { path = "examples/ideal_gas.rs" }
